"""Add personal_profiles table

Revision ID: 2eaa9d975b79
Revises: 33d85e6f18ff
Create Date: 2026-01-13 13:02:01.462498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2eaa9d975b79'
down_revision: Union[str, Sequence[str], None] = '33d85e6f18ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personal_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('occupation', sa.String(), nullable=True),
    sa.Column('education', sa.String(), nullable=True),
    sa.Column('marital_status', sa.String(), nullable=True),
    sa.Column('hobbies', sa.Text(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('life_events', sa.Text(), nullable=True),
    sa.Column('avatar_path', sa.String(), nullable=True),
    sa.Column('last_updated', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personal_profiles_user_id'), 'personal_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scores_username'), table_name='scores')
    op.drop_index(op.f('ix_scores_user_id'), table_name='scores')
    op.drop_index(op.f('ix_scores_total_score'), table_name='scores')
    op.drop_index(op.f('ix_scores_timestamp'), table_name='scores')
    op.drop_index(op.f('ix_scores_detailed_age_group'), table_name='scores')
    op.drop_index(op.f('ix_scores_age'), table_name='scores')
    op.drop_index('idx_score_username_timestamp', table_name='scores')
    op.drop_index('idx_score_user_timestamp', table_name='scores')
    op.drop_index('idx_score_agegroup_score', table_name='scores')
    op.drop_index('idx_score_age_score', table_name='scores')
    op.drop_index(op.f('ix_responses_username'), table_name='responses')
    op.drop_index(op.f('ix_responses_user_id'), table_name='responses')
    op.drop_index(op.f('ix_responses_timestamp'), table_name='responses')
    op.drop_index(op.f('ix_responses_response_value'), table_name='responses')
    op.drop_index(op.f('ix_responses_question_id'), table_name='responses')
    op.drop_index(op.f('ix_responses_detailed_age_group'), table_name='responses')
    op.drop_index(op.f('ix_responses_age_group'), table_name='responses')
    op.drop_index('idx_response_username_timestamp', table_name='responses')
    op.drop_index('idx_response_user_timestamp', table_name='responses')
    op.drop_index('idx_response_user_question', table_name='responses')
    op.drop_index('idx_response_question_timestamp', table_name='responses')
    op.drop_index('idx_response_agegroup_timestamp', table_name='responses')
    op.add_column('question_category', sa.Column('description', sa.TEXT(), nullable=True))
    op.alter_column('question_category', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('question_bank', 'question_text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.add_column('journal_entries', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'journal_entries', 'users', ['user_id'], ['id'])
    op.create_table('admin_users',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('username', sa.TEXT(), nullable=False),
    sa.Column('password_hash', sa.TEXT(), nullable=False),
    sa.Column('role', sa.TEXT(), server_default=sa.text("'admin'"), nullable=True),
    sa.Column('created_at', sa.TEXT(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('question_metadata',
    sa.Column('question_id', sa.INTEGER(), nullable=False),
    sa.Column('source', sa.VARCHAR(), nullable=True),
    sa.Column('version', sa.VARCHAR(), nullable=True),
    sa.Column('tags', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_table('questions',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('text', sa.TEXT(), nullable=False),
    sa.Column('category', sa.TEXT(), server_default=sa.text("'General'"), nullable=True),
    sa.Column('age_min', sa.INTEGER(), server_default=sa.text('(12)'), nullable=True),
    sa.Column('age_max', sa.INTEGER(), server_default=sa.text('(100)'), nullable=True),
    sa.Column('difficulty', sa.INTEGER(), server_default=sa.text('3'), nullable=True),
    sa.Column('weight', sa.REAL(), server_default=sa.text('(1.0)'), nullable=True),
    sa.Column('created_at', sa.TEXT(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TEXT(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('is_active', sa.INTEGER(), server_default=sa.text('1'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_personal_profiles_user_id'), table_name='personal_profiles')
    op.drop_table('personal_profiles')
    # ### end Alembic commands ###
