"""add_daily_metrics_to_journal

Revision ID: c62bcfa45980
Revises: b33b18452387
Create Date: 2026-01-12 21:24:31.807143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c62bcfa45980'
down_revision: Union[str, Sequence[str], None] = 'b33b18452387'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Tables already exist, commenting out to prevent errors
    # op.create_table('statistics_cache',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('stat_name', sa.String(), nullable=True),
    # sa.Column('stat_value', sa.Float(), nullable=True),
    # sa.Column('stat_json', sa.Text(), nullable=True),
    # sa.Column('calculated_at', sa.String(), nullable=True),
    # sa.Column('valid_until', sa.String(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index('idx_stats_name_valid', 'statistics_cache', ['stat_name', 'valid_until'], unique=False)
    # op.create_index(op.f('ix_statistics_cache_stat_name'), 'statistics_cache', ['stat_name'], unique=True)
    # op.create_index(op.f('ix_statistics_cache_valid_until'), 'statistics_cache', ['valid_until'], unique=False)
    # op.create_table('question_cache',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('question_id', sa.Integer(), nullable=True),
    # sa.Column('question_text', sa.Text(), nullable=False),
    # sa.Column('category_id', sa.Integer(), nullable=True),
    # sa.Column('difficulty', sa.Integer(), nullable=True),
    # sa.Column('is_active', sa.Integer(), nullable=True),
    # sa.Column('min_age', sa.Integer(), nullable=True),
    # sa.Column('max_age', sa.Integer(), nullable=True),
    # sa.Column('tooltip', sa.Text(), nullable=True),
    # sa.Column('cached_at', sa.String(), nullable=True),
    # sa.Column('access_count', sa.Integer(), nullable=True),
    # sa.ForeignKeyConstraint(['question_id'], ['question_bank.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index('idx_cache_access_time', 'question_cache', ['access_count', 'cached_at'], unique=False)
    # op.create_index('idx_cache_active_difficulty', 'question_cache', ['is_active', 'difficulty'], unique=False)
    # op.create_index('idx_cache_category_active', 'question_cache', ['category_id', 'is_active'], unique=False)
    # op.create_index(op.f('ix_question_cache_access_count'), 'question_cache', ['access_count'], unique=False)
    # op.create_index(op.f('ix_question_cache_category_id'), 'question_cache', ['category_id'], unique=False)
    # op.create_index(op.f('ix_question_cache_difficulty'), 'question_cache', ['difficulty'], unique=False)
    # op.create_index(op.f('ix_question_cache_is_active'), 'question_cache', ['is_active'], unique=False)
    # op.create_index(op.f('ix_question_cache_question_id'), 'question_cache', ['question_id'], unique=True)
    # op.create_table('user_settings',
    # sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('user_id', sa.Integer(), nullable=False),
    # sa.Column('theme', sa.String(), nullable=True),
    # sa.Column('question_count', sa.Integer(), nullable=True),
    # sa.Column('sound_enabled', sa.Boolean(), nullable=True),
    # sa.Column('notifications_enabled', sa.Boolean(), nullable=True),
    # sa.Column('language', sa.String(), nullable=True),
    # sa.Column('updated_at', sa.String(), nullable=True),
    # sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index(op.f('ix_user_settings_user_id'), 'user_settings', ['user_id'], unique=True)
    # op.drop_table('question_metadata')
    
    
    
    # NEW COLUMNS (Keeping these)
    op.add_column('journal_entries', sa.Column('sleep_hours', sa.Float(), nullable=True))
    op.add_column('journal_entries', sa.Column('sleep_quality', sa.Integer(), nullable=True))
    op.add_column('journal_entries', sa.Column('energy_level', sa.Integer(), nullable=True))
    op.add_column('journal_entries', sa.Column('work_hours', sa.Float(), nullable=True))
    
    # op.drop_column('journal_entries', 'user_id')
    # op.alter_column('question_bank', 'question_text',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(),
    #            nullable=True)
    # op.alter_column('question_category', 'name',
    #            existing_type=sa.VARCHAR(),
    #            nullable=True)
    # op.drop_column('question_category', 'description')
    
    # Existing indexes likely exist
    # op.create_index('idx_response_agegroup_timestamp', 'responses', ['detailed_age_group', 'timestamp'], unique=False)
    # op.create_index('idx_response_question_timestamp', 'responses', ['question_id', 'timestamp'], unique=False)
    # op.create_index('idx_response_user_question', 'responses', ['user_id', 'question_id'], unique=False)
    # op.create_index('idx_response_user_timestamp', 'responses', ['user_id', 'timestamp'], unique=False)
    # op.create_index('idx_response_username_timestamp', 'responses', ['username', 'timestamp'], unique=False)
    # op.create_index(op.f('ix_responses_age_group'), 'responses', ['age_group'], unique=False)
    # op.create_index(op.f('ix_responses_detailed_age_group'), 'responses', ['detailed_age_group'], unique=False)
    # op.create_index(op.f('ix_responses_question_id'), 'responses', ['question_id'], unique=False)
    # op.create_index(op.f('ix_responses_response_value'), 'responses', ['response_value'], unique=False)
    # op.create_index(op.f('ix_responses_timestamp'), 'responses', ['timestamp'], unique=False)
    # op.create_index(op.f('ix_responses_user_id'), 'responses', ['user_id'], unique=False)
    # op.create_index(op.f('ix_responses_username'), 'responses', ['username'], unique=False)
    
    # Score columns might be needed if they don't exist, but risking it failing if they do.
    # We will try to add them. If it fails, we'll know.
    # Using 'if not exists' logic is hard here without custom code.
    # Let's hope they don't exist or we will error out on 'duplicate column'
    # op.add_column('scores', sa.Column('sentiment_score', sa.Float(), nullable=True))
    # op.add_column('scores', sa.Column('reflection_text', sa.Text(), nullable=True))
    # op.add_column('scores', sa.Column('is_rushed', sa.Boolean(), nullable=True))
    # op.add_column('scores', sa.Column('is_inconsistent', sa.Boolean(), nullable=True))
    
    # op.create_index('idx_score_age_score', 'scores', ['age', 'total_score'], unique=False)
    # op.create_index('idx_score_agegroup_score', 'scores', ['detailed_age_group', 'total_score'], unique=False)
    # op.create_index('idx_score_user_timestamp', 'scores', ['user_id', 'timestamp'], unique=False)
    # op.create_index('idx_score_username_timestamp', 'scores', ['username', 'timestamp'], unique=False)
    # op.create_index(op.f('ix_scores_age'), 'scores', ['age'], unique=False)
    # op.create_index(op.f('ix_scores_detailed_age_group'), 'scores', ['detailed_age_group'], unique=False)
    # op.create_index(op.f('ix_scores_timestamp'), 'scores', ['timestamp'], unique=False)
    # op.create_index(op.f('ix_scores_total_score'), 'scores', ['total_score'], unique=False)
    # op.create_index(op.f('ix_scores_user_id'), 'scores', ['user_id'], unique=False)
    # op.create_index(op.f('ix_scores_username'), 'scores', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scores_username'), table_name='scores')
    op.drop_index(op.f('ix_scores_user_id'), table_name='scores')
    op.drop_index(op.f('ix_scores_total_score'), table_name='scores')
    op.drop_index(op.f('ix_scores_timestamp'), table_name='scores')
    op.drop_index(op.f('ix_scores_detailed_age_group'), table_name='scores')
    op.drop_index(op.f('ix_scores_age'), table_name='scores')
    op.drop_index('idx_score_username_timestamp', table_name='scores')
    op.drop_index('idx_score_user_timestamp', table_name='scores')
    op.drop_index('idx_score_agegroup_score', table_name='scores')
    op.drop_index('idx_score_age_score', table_name='scores')
    op.drop_column('scores', 'is_inconsistent')
    op.drop_column('scores', 'is_rushed')
    op.drop_column('scores', 'reflection_text')
    op.drop_column('scores', 'sentiment_score')
    op.drop_index(op.f('ix_responses_username'), table_name='responses')
    op.drop_index(op.f('ix_responses_user_id'), table_name='responses')
    op.drop_index(op.f('ix_responses_timestamp'), table_name='responses')
    op.drop_index(op.f('ix_responses_response_value'), table_name='responses')
    op.drop_index(op.f('ix_responses_question_id'), table_name='responses')
    op.drop_index(op.f('ix_responses_detailed_age_group'), table_name='responses')
    op.drop_index(op.f('ix_responses_age_group'), table_name='responses')
    op.drop_index('idx_response_username_timestamp', table_name='responses')
    op.drop_index('idx_response_user_timestamp', table_name='responses')
    op.drop_index('idx_response_user_question', table_name='responses')
    op.drop_index('idx_response_question_timestamp', table_name='responses')
    op.drop_index('idx_response_agegroup_timestamp', table_name='responses')
    op.add_column('question_category', sa.Column('description', sa.TEXT(), nullable=True))
    op.alter_column('question_category', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('question_bank', 'question_text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.add_column('journal_entries', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.drop_column('journal_entries', 'work_hours')
    op.drop_column('journal_entries', 'energy_level')
    op.drop_column('journal_entries', 'sleep_quality')
    op.drop_column('journal_entries', 'sleep_hours')
    op.create_table('question_metadata',
    sa.Column('question_id', sa.INTEGER(), nullable=False),
    sa.Column('source', sa.VARCHAR(), nullable=True),
    sa.Column('version', sa.VARCHAR(), nullable=True),
    sa.Column('tags', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.drop_index(op.f('ix_user_settings_user_id'), table_name='user_settings')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_question_cache_question_id'), table_name='question_cache')
    op.drop_index(op.f('ix_question_cache_is_active'), table_name='question_cache')
    op.drop_index(op.f('ix_question_cache_difficulty'), table_name='question_cache')
    op.drop_index(op.f('ix_question_cache_category_id'), table_name='question_cache')
    op.drop_index(op.f('ix_question_cache_access_count'), table_name='question_cache')
    op.drop_index('idx_cache_category_active', table_name='question_cache')
    op.drop_index('idx_cache_active_difficulty', table_name='question_cache')
    op.drop_index('idx_cache_access_time', table_name='question_cache')
    op.drop_table('question_cache')
    op.drop_index(op.f('ix_statistics_cache_valid_until'), table_name='statistics_cache')
    op.drop_index(op.f('ix_statistics_cache_stat_name'), table_name='statistics_cache')
    op.drop_index('idx_stats_name_valid', table_name='statistics_cache')
    op.drop_table('statistics_cache')
    # ### end Alembic commands ###
