"""feat_all_profile_gaps

Revision ID: f62984ab805f
Revises: 1fc597e57c19
Create Date: 2026-01-14 14:02:21.099394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f62984ab805f'
down_revision: Union[str, Sequence[str], None] = '1fc597e57c19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statistics_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stat_name', sa.String(), nullable=True),
    sa.Column('stat_value', sa.Float(), nullable=True),
    sa.Column('stat_json', sa.Text(), nullable=True),
    sa.Column('calculated_at', sa.String(), nullable=True),
    sa.Column('valid_until', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('statistics_cache', schema=None) as batch_op:
        batch_op.create_index('idx_stats_name_valid', ['stat_name', 'valid_until'], unique=False)
        batch_op.create_index(batch_op.f('ix_statistics_cache_stat_name'), ['stat_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_statistics_cache_valid_until'), ['valid_until'], unique=False)

    op.create_table('question_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('min_age', sa.Integer(), nullable=True),
    sa.Column('max_age', sa.Integer(), nullable=True),
    sa.Column('tooltip', sa.Text(), nullable=True),
    sa.Column('cached_at', sa.String(), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question_bank.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question_cache', schema=None) as batch_op:
        batch_op.create_index('idx_cache_access_time', ['access_count', 'cached_at'], unique=False)
        batch_op.create_index('idx_cache_active_difficulty', ['is_active', 'difficulty'], unique=False)
        batch_op.create_index('idx_cache_category_active', ['category_id', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_cache_access_count'), ['access_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_cache_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_cache_difficulty'), ['difficulty'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_cache_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_cache_question_id'), ['question_id'], unique=True)

    op.create_table('satisfaction_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('month_year', sa.String(), nullable=True),
    sa.Column('avg_satisfaction', sa.Float(), nullable=True),
    sa.Column('trend', sa.String(), nullable=True),
    sa.Column('insights', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('satisfaction_history', schema=None) as batch_op:
        batch_op.create_index('idx_satisfaction_history_user_month', ['user_id', 'month_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_satisfaction_history_month_year'), ['month_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_satisfaction_history_user_id'), ['user_id'], unique=False)

    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('theme', sa.String(), nullable=True),
    sa.Column('question_count', sa.Integer(), nullable=True),
    sa.Column('sound_enabled', sa.Boolean(), nullable=True),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_settings_user_id'), ['user_id'], unique=True)

    op.create_table('satisfaction_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.Column('satisfaction_score', sa.Integer(), nullable=True),
    sa.Column('satisfaction_category', sa.String(), nullable=True),
    sa.Column('positive_factors', sa.Text(), nullable=True),
    sa.Column('negative_factors', sa.Text(), nullable=True),
    sa.Column('improvement_suggestions', sa.Text(), nullable=True),
    sa.Column('context', sa.String(), nullable=True),
    sa.Column('duration_months', sa.Integer(), nullable=True),
    sa.Column('eq_score_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['eq_score_id'], ['scores.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('satisfaction_records', schema=None) as batch_op:
        batch_op.create_index('idx_satisfaction_category_score', ['satisfaction_category', 'satisfaction_score'], unique=False)
        batch_op.create_index('idx_satisfaction_context', ['context', 'satisfaction_score'], unique=False)
        batch_op.create_index('idx_satisfaction_user_time', ['user_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_satisfaction_records_eq_score_id'), ['eq_score_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_satisfaction_records_satisfaction_category'), ['satisfaction_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_satisfaction_records_satisfaction_score'), ['satisfaction_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_satisfaction_records_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_satisfaction_records_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_satisfaction_records_username'), ['username'], unique=False)

    op.drop_table('question_metadata')
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    with op.batch_alter_table('medical_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('surgeries', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('therapy_history', sa.Text(), nullable=True))

    with op.batch_alter_table('personal_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('society_contribution', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('life_pov', sa.Text(), nullable=True))

    with op.batch_alter_table('question_bank', schema=None) as batch_op:
        batch_op.alter_column('question_text',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)

    with op.batch_alter_table('question_category', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('description')

    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.create_index('idx_response_agegroup_timestamp', ['detailed_age_group', 'timestamp'], unique=False)
        batch_op.create_index('idx_response_question_timestamp', ['question_id', 'timestamp'], unique=False)
        batch_op.create_index('idx_response_user_question', ['user_id', 'question_id'], unique=False)
        batch_op.create_index('idx_response_user_timestamp', ['user_id', 'timestamp'], unique=False)
        batch_op.create_index('idx_response_username_timestamp', ['username', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_responses_age_group'), ['age_group'], unique=False)
        batch_op.create_index(batch_op.f('ix_responses_detailed_age_group'), ['detailed_age_group'], unique=False)
        batch_op.create_index(batch_op.f('ix_responses_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_responses_response_value'), ['response_value'], unique=False)
        batch_op.create_index(batch_op.f('ix_responses_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_responses_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_responses_username'), ['username'], unique=False)

    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sentiment_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('reflection_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_rushed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_inconsistent', sa.Boolean(), nullable=True))
        batch_op.create_index('idx_score_age_score', ['age', 'total_score'], unique=False)
        batch_op.create_index('idx_score_agegroup_score', ['detailed_age_group', 'total_score'], unique=False)
        batch_op.create_index('idx_score_user_timestamp', ['user_id', 'timestamp'], unique=False)
        batch_op.create_index('idx_score_username_timestamp', ['username', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_scores_age'), ['age'], unique=False)
        batch_op.create_index(batch_op.f('ix_scores_detailed_age_group'), ['detailed_age_group'], unique=False)
        batch_op.create_index(batch_op.f('ix_scores_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_scores_total_score'), ['total_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_scores_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scores_username'), ['username'], unique=False)

    with op.batch_alter_table('user_strengths', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comm_style', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_strengths', schema=None) as batch_op:
        batch_op.drop_column('comm_style')

    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scores_username'))
        batch_op.drop_index(batch_op.f('ix_scores_user_id'))
        batch_op.drop_index(batch_op.f('ix_scores_total_score'))
        batch_op.drop_index(batch_op.f('ix_scores_timestamp'))
        batch_op.drop_index(batch_op.f('ix_scores_detailed_age_group'))
        batch_op.drop_index(batch_op.f('ix_scores_age'))
        batch_op.drop_index('idx_score_username_timestamp')
        batch_op.drop_index('idx_score_user_timestamp')
        batch_op.drop_index('idx_score_agegroup_score')
        batch_op.drop_index('idx_score_age_score')
        batch_op.drop_column('is_inconsistent')
        batch_op.drop_column('is_rushed')
        batch_op.drop_column('reflection_text')
        batch_op.drop_column('sentiment_score')

    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_responses_username'))
        batch_op.drop_index(batch_op.f('ix_responses_user_id'))
        batch_op.drop_index(batch_op.f('ix_responses_timestamp'))
        batch_op.drop_index(batch_op.f('ix_responses_response_value'))
        batch_op.drop_index(batch_op.f('ix_responses_question_id'))
        batch_op.drop_index(batch_op.f('ix_responses_detailed_age_group'))
        batch_op.drop_index(batch_op.f('ix_responses_age_group'))
        batch_op.drop_index('idx_response_username_timestamp')
        batch_op.drop_index('idx_response_user_timestamp')
        batch_op.drop_index('idx_response_user_question')
        batch_op.drop_index('idx_response_question_timestamp')
        batch_op.drop_index('idx_response_agegroup_timestamp')

    with op.batch_alter_table('question_category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('question_bank', schema=None) as batch_op:
        batch_op.alter_column('question_text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('personal_profiles', schema=None) as batch_op:
        batch_op.drop_column('life_pov')
        batch_op.drop_column('society_contribution')

    with op.batch_alter_table('medical_profiles', schema=None) as batch_op:
        batch_op.drop_column('therapy_history')
        batch_op.drop_column('surgeries')

    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))

    op.create_table('question_metadata',
    sa.Column('question_id', sa.INTEGER(), nullable=False),
    sa.Column('source', sa.VARCHAR(), nullable=True),
    sa.Column('version', sa.VARCHAR(), nullable=True),
    sa.Column('tags', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('question_id')
    )
    with op.batch_alter_table('satisfaction_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_satisfaction_records_username'))
        batch_op.drop_index(batch_op.f('ix_satisfaction_records_user_id'))
        batch_op.drop_index(batch_op.f('ix_satisfaction_records_timestamp'))
        batch_op.drop_index(batch_op.f('ix_satisfaction_records_satisfaction_score'))
        batch_op.drop_index(batch_op.f('ix_satisfaction_records_satisfaction_category'))
        batch_op.drop_index(batch_op.f('ix_satisfaction_records_eq_score_id'))
        batch_op.drop_index('idx_satisfaction_user_time')
        batch_op.drop_index('idx_satisfaction_context')
        batch_op.drop_index('idx_satisfaction_category_score')

    op.drop_table('satisfaction_records')
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_settings_user_id'))

    op.drop_table('user_settings')
    with op.batch_alter_table('satisfaction_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_satisfaction_history_user_id'))
        batch_op.drop_index(batch_op.f('ix_satisfaction_history_month_year'))
        batch_op.drop_index('idx_satisfaction_history_user_month')

    op.drop_table('satisfaction_history')
    with op.batch_alter_table('question_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_cache_question_id'))
        batch_op.drop_index(batch_op.f('ix_question_cache_is_active'))
        batch_op.drop_index(batch_op.f('ix_question_cache_difficulty'))
        batch_op.drop_index(batch_op.f('ix_question_cache_category_id'))
        batch_op.drop_index(batch_op.f('ix_question_cache_access_count'))
        batch_op.drop_index('idx_cache_category_active')
        batch_op.drop_index('idx_cache_active_difficulty')
        batch_op.drop_index('idx_cache_access_time')

    op.drop_table('question_cache')
    with op.batch_alter_table('statistics_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_statistics_cache_valid_until'))
        batch_op.drop_index(batch_op.f('ix_statistics_cache_stat_name'))
        batch_op.drop_index('idx_stats_name_valid')

    op.drop_table('statistics_cache')
    # ### end Alembic commands ###
